version: '3.8'

services:
  postgres_test:
    image: postgres:15
    container_name: postgres_test
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"  # Porta diversa per non confliggere
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - test_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis_test:
    image: redis:7-alpine
    container_name: redis_test
    ports:
      - "6380:6379"  # Porta diversa per non confliggere
    volumes:
      - redis_test_data:/data
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
  redis_test_data:

networks:
  test_network:
    driver: bridge